### ISSUE TITLE
Core Team vs Community proposals?

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/swift-proposal-analyzer#4]
It would be nice to be able to specify if an author is on the Core Team or not.

``` swift
author.isCoreTeam
```

We'll probably have to manually maintain a list of Core Team members. Maybe we could use the GitHub API?

```
coreTeam.contains(author)
```

**Comment by digoreis** [comment]
You say to use that API: https://api.github.com/orgs/apple/public_members

**Comment by jessesquires** [comment]
@digoreis Hm... 🤔 that list doesn't look completely correct to me.

**Comment by digoreis** [comment]
@jessesquires  another option is https://gist.githubusercontent.com/digoreis/5c13bac6150b2831ec9126cc2bea54fc/raw/deacc11faaf53451b81998dda2238b24504f06d6/core-team-swift.json

**Comment by jessesquires** [comment]
Hm, at that point, we might as well maintain a hard-coded dictionary in the framework 😅 

I don't think we're going to be able to reliably get this data from GitHub or anywhere else.

**Comment by kiliankoe** [comment]
Please correct me if I'm wrong, but wouldn't this list cover it? 😊

https://github.com/apple/swift/blob/master/CODE_OWNERS.TXT

**Comment by jessesquires** [comment]
@kiliankoe Ha, not quite 😄 

Core Team:
https://swift.org/community/#community-structure

But, that brings up a good point. There are a few different roles to consider here:

1. core team member
2. code owner
3. works at apple
